apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: teenage-llama-go 
  janus-idp.io/tekton: teenage-llama-go
  backstage.io/kubernetes-id: teenage-llama-go
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: teenage-llama-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  