apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: teenage-llama-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: teenage-llama-go 
  name: teenage-llama-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: teenage-llama-go 
